{% set name = "deepEMhancer" %}
{% set version = "0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: "../"
#  git_rev: "master"
#  git_url: "https://github.com/rsanchezgarc/deepEMhancer/"

build:
  number: 0
  entry_points:
    - deepemhancer=deepEMhancer.exeDeepEMhancer:commanLineFun
  script: "{{ PYTHON }} -m pip install . -vv && {{ PYTHON }} -m pip install git+https://www.github.com/keras-team/keras-contrib.git@3fc5ef709e061416f4bc8a92ca3750c824b5d2b0 && {{ PYTHON }} -m pip install https://files.pythonhosted.org/packages/46/a2/5e7675410a187a8f35f321f3d3bf9e5116aec64a4b37ab34e07353fe30a3/keras-radam-0.12.0.tar.gz "

requirements:
  build:
    - numpy ==1.16.*
    - setuptools
    - joblib ==0.13.*
    - keras ==2.2.*
    - mrcfile ==1.1.2
    - pandas ==0.25.*
    - pip
    - python ==3.6.*
    - requests ==2.22.*
    - scikit-image ==0.15.*
    - scipy ==1.3.1
    - tensorflow-gpu ==1.14.*
    - tqdm ==4.42
  run:
    - numpy ==1.16.*
    - joblib ==0.13.*
    - joblib ==0.13.*
    - keras ==2.2.*
    - mrcfile ==1.1.2
    - pandas ==0.25.*
    - pip
    - python ==3.6.*
    - requests ==2.22.*
    - scikit-image ==0.15.*
    - scipy ==1.3.1
    - tensorflow-gpu ==1.14.*
    - tqdm ==4.42

test:
  imports:
    - deepEMhancer
    - deepEMhancer.applyProcessVol
    - deepEMhancer.utils
  commands:
    - deepemhancer --help
    - python -c "import keras; import keras_contrib"

about:
  home: "https://github.com/rsanchezgarc/deepEMhancer"
  license: Apache 2.0
  license_family: APACHE
  license_file:
  summary: "Deep learning for cryo-EM maps post-processing"
  doc_url:
  dev_url: