{% set name = "deepEMhancer" %}
{% set version = "0.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: "../"
#  git_rev: "master"
#  git_url: "https://github.com/rsanchezgarc/deepEMhancer/"

build:
  number: 0
  entry_points:
    - deepemhancer=deepEMhancer.exeDeepEMhancer:commanLineFun
  script: "{{ PYTHON }} -m pip install . -vv --no-deps && echo 'DONE' "

requirements:
  host:
    - setuptools
    - pip
    - python >=3.10,<3.14
  run:
    - h5py >=3.11,<3.15
    - mrcfile >=1.5,<1.6
    - numpy >=1.26,<2.3
    - python >=3.10,<3.14
    - requests >=2.32,<3
    - scikit-image >=0.24,<0.27
    - scipy >=1.13,<1.18
    - tensorflow >=2.21,<2.22
    - tqdm >=4.67,<5
test:
  imports:
    - deepEMhancer
    - deepEMhancer.applyProcessVol
    - deepEMhancer.utils
  commands:
    - deepemhancer --help
    - python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"

about:
  home: "https://github.com/rsanchezgarc/deepEMhancer"
  license: Apache 2.0
  license_family: APACHE
  license_file:
  summary: "Deep learning for cryo-EM maps post-processing"
  doc_url:
  dev_url:
